Fix initial connection failure
When launching this backend, this plugin would consistently log the
following two errors:

    ValueError: Port could not be cast to integer value as '(4455,)'
    2026-03-25 05:07:56.121 | ERROR    | __main__:connect_to:67 - Failed to connect to OBS: Port could not be cast to integer value as '(4455,)'

The plugin would function correctly after this.

This patch removes a stray comma which was causing this error to
appear.